### ISSUE TITLE
HPE_INVALID_CONSTANT on rcon command

### ISSUE THREAD

**Issue by cornholio21** [kennethrisa/discord-rustserverstatus#49]
Tried to run rcon commands from discord. Getting this error message in console output. RustAdmin works fine with rcon.

Error: Parse Error: Expected HTTP/
    at Socket.socketOnData (_http_client.js:474:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  bytesParsed: 0,
  code: 'HPE_INVALID_CONSTANT',
  reason: 'Expected HTTP/',
  rawPacket: <Buffer 88 02 03 e8>
}

**Comment by kennethrisa** [comment]
Fixed by release v1.2.0

**Comment by cornholio21** [comment]
It's still happening with new NodeJS and new version.
