### ISSUE TITLE
Handle ERR_UNHANDLED_ERROR

### ISSUE THREAD

**Issue by kennethrisa** [kennethrisa/discord-rustserverstatus#9]
Find a way to handle ERR_UNHANDLED_ERROR.

Error log from using docker:

```
events.js:171
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:169:17)
    at WebSocketConnection.onError (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/usr/src/app/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:180:13)
    at _receiver.cleanup (/usr/src/app/node_modules/ws/lib/websocket.js:211:14)
    at Receiver.cleanup (/usr/src/app/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/usr/src/app/node_modules/ws/lib/websocket.js:206:20)
    at TLSSocket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

**Comment by kennethrisa** [comment]
Merged pr https://github.com/kennethrisa/discord-rustserverstatus/pull/10 to handle on error events
